name: Release APK

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0, v1.1.0, etc.

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build debug APK
      run: ./gradlew assembleDebug
      
    - name: Build release APK
      run: ./gradlew assembleRelease
      
    - name: Get version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      
    - name: Check APK files
      run: |
        echo "Checking APK files..."
        ls -la app/build/outputs/apk/debug/
        ls -la app/build/outputs/apk/release/
        
    - name: Create Release with gh CLI
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create ${{ steps.get_version.outputs.VERSION }} \
          --title "Kids Calculator ${{ steps.get_version.outputs.VERSION }}" \
          --notes "## Kids Calculator ${{ steps.get_version.outputs.VERSION }}
          
          ### 🎯 Features
          - Child-friendly calculator with large buttons
          - Russian text-to-speech support
          - Mathematical operations: addition, subtraction, multiplication, division
          - Voice feedback for numbers and operations
          
          ### 📱 Installation
          1. Download the APK file below
          2. Enable \"Install from unknown sources\" in your Android settings
          3. Install the APK file
          
          ### 🔧 Technical Details
          - **Target Android Version**: API 34 (Android 14)
          - **Minimum Android Version**: API 21 (Android 5.0)
          - **Architecture**: Universal (ARM64, ARM32, x86_64, x86)
          
          ### 📋 What's New
          - Fixed NumberFormatException crash with comma decimal input
          - Fixed release APK installation issues
          - Added Russian error messages
          - Improved error handling for TTS operations" \
          app/build/outputs/apk/debug/app-debug.apk#kids-calculator-${{ steps.get_version.outputs.VERSION }}-debug.apk \
          app/build/outputs/apk/release/app-release.apk#kids-calculator-${{ steps.get_version.outputs.VERSION }}-release.apk